#!/usr/bin/env python3
"""
build_gazetteer.py — regenerate engine/mappings/geo/cities.json from GeoNames.

Dev-time tool (NOT part of the runtime engine — the engine stays offline; it
only reads the generated JSON). Re-run when refreshing the bundled gazetteer:

    curl -LO https://download.geonames.org/export/dump/cities15000.zip && unzip cities15000.zip
    curl -LO https://download.geonames.org/export/dump/admin1CodesASCII.txt
    curl -LO https://download.geonames.org/export/dump/countryInfo.txt
    python3 packaging/build_gazetteer.py <dir-with-those-files>

Data: GeoNames (https://www.geonames.org), licensed CC-BY 4.0 — attribution is
kept in engine/references/geonames-attribution.md and inside the JSON header.

Output shape (compact arrays to keep the bundled file small):
  {"_comment": …, "_license": …,
   "countries": {"us": ["united states", "usa", …], …},   # cc -> match names
   "cities": [[name, cc, admin1_name, lat, lng, population], …]}
"""
import json
import sys
from pathlib import Path

MIN_POP = 15000


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else ".").expanduser()
    out = Path(__file__).resolve().parent.parent / "engine" / "mappings" / "geo" / "cities.json"

    # admin1 code ("US.CA") -> display name ("California")
    admin = {}
    for ln in (src / "admin1CodesASCII.txt").read_text(encoding="utf-8").splitlines():
        parts = ln.split("\t")
        if len(parts) >= 2:
            admin[parts[0]] = parts[1]

    # country code -> the names a location string might use for it
    countries = {}
    for ln in (src / "countryInfo.txt").read_text(encoding="utf-8").splitlines():
        if ln.startswith("#"):
            continue
        p = ln.split("\t")
        if len(p) < 5:
            continue
        cc = p[0].lower()
        names = {p[4].lower(), cc, p[1].lower()}      # name, iso2, iso3
        countries[cc] = sorted(n for n in names if n)

    cities = []
    for ln in (src / "cities15000.txt").read_text(encoding="utf-8").splitlines():
        p = ln.split("\t")
        # geonameid, name, asciiname, alternatenames, lat, lng, fclass, fcode,
        # country, cc2, admin1, admin2, admin3, admin4, population, …
        if len(p) < 15:
            continue
        name, ascii_name = p[1], p[2]
        lat, lng = round(float(p[4]), 4), round(float(p[5]), 4)
        cc = p[8].lower()
        pop = int(p[14] or 0)
        if pop < MIN_POP:
            continue
        a1 = admin.get(f"{p[8]}.{p[10]}", "")
        cities.append([name, cc, a1, lat, lng, pop])
        # keep the ascii variant only when it differs (é vs e lookups)
        if ascii_name and ascii_name != name:
            cities.append([ascii_name, cc, a1, lat, lng, pop])

    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "_comment": "Offline city gazetteer for build-time geocoding (engine/scripts/geocode.py). "
                    "Generated by packaging/build_gazetteer.py — do not edit by hand.",
        "_license": "Data (c) GeoNames (geonames.org), CC-BY 4.0 — see engine/references/geonames-attribution.md",
        "countries": countries,
        "cities": cities,
    }
    out.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
                   encoding="utf-8")
    print(f"wrote {out} — {len(cities)} city rows, {out.stat().st_size/1e6:.1f} MB")


if __name__ == "__main__":
    main()
